[workspace]
members = [
  "crates/mpera",
  "crates/autark-dataframe",
  "crates/autark-reader",
  "crates/autark-sinks",
  "crates/autark-client",
  "crates/autark-tensor",
  "crates/autark-error",
  "crates/with-tinygrad"
]

resolver = "3"
