[package]
name = "autark-reader"
version = "0.1.0"
edition = "2024"

[dependencies]
autark-dataframe = { path = "../autark-dataframe" }
autark-error = { path = "../autark-error" }
arrow = "=56.2.0"
arrow-csv = "=56.2.0"
arrow-json = "=56.2.0"
