[package]
name = "autark-dataframe"
version = "0.1.0"
edition = "2024"

[dependencies]
autark-tensor = { path = "../autark-tensor" }
autark-error = { path = "../autark-error" }

arrow = { version = "=56.2.0", features = [ "prettyprint" ] }
