[package]
name = "autark-enhanced-reader"
version = "0.1.0"
edition = "2024"

[dependencies]
autark-error = { path = "../autark-error" }
reqwest = { version = "0.12", default-features = false, features = ["blocking", "rustls-tls"] }
