[package]
name = "autark-sinks"
version = "0.1.0"
edition = "2024"

[dependencies]
autark_error = { path = "../autark-error" }
mpera = { path = "../mpera" }

arrow = { version = "=56.2.0", features = [ "prettyprint" ] }
